<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="Promise.js"></script>
</head>
<body>
    
    <script>
        //Promise是类对象
        //resolve是静态方法
        /*
            Promise.resolve()
            - resolve返回的是一个promise实例对象
            - 它的状态永远都是fulfilled
            - 也可以嵌套,Promise.resolve("321")
                - 相同于嵌套了一个promise对象
        */
        // console.log(Promise.resolve(
        //         Promise.reject("321")
        //     )
        // );

        // Promise.resolve("123").then(value=>{
        //     console.log(">>>",value);
        // })

        /*
            Promise.resolve("123")
                - state = "fulfilled"
                - value = "123"
            Promise.resolve(实例对象)
                - 外层
                - 实例对象把状态给外层了
                - 实例对象把值也给外层了
        */
        // Promise.resolve(Promise.resolve("123"))


        //reject返回的是promise对象
        // Promise.reject("error");


        //promise中断链条
        /*
            代码不处理 或写上return不可以中断链条的
                - 不处理则返回 return undefined
                - return 123
                - return 的状态是fulfilled
            reject() throw 的状态 rejected
            

        */
        
        let p = new Promise((resolve,reject)=>{
            resolve("123");
        }).then(value=>{
            return new Promise((resolve,reject)=>{
                resolve(value + "123");//123123
            })
        }).then(value=>{
            

        }).then(value=>{
            return new Promise((resolve,reject)=>{
                resolve(value + "123");//123123123123
            })
        }).then(value=>{
            console.info(value);
        }).catch(reason=>{
            console.error("报错了,大哥");
        })


    </script>


</body>
</html>